### ISSUE TITLE
purchasePackage does nothing and throw no exception

### ISSUE THREAD

**Issue by jezsung** [RevenueCat/purchases-flutter#139]
<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-KR)
    • Flutter version 1.22.4 at /usr/local/Caskroom/flutter/1.22.4/flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jaesunghong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Jaesung의 iPhone (mobile) • 48006f05f9f84f9f0771134bb1d76016876695a3 • ios • iOS 14.2
```
</details>

<details>
  <summary>pubspec.yaml</summary>
  
``` yaml
name: flutter_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  admob_flutter: ^1.0.1
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  clipboard: ^0.1.2+8
  cloud_firestore: ^0.14.3
  device_preview: ^0.4.8
  equatable: ^1.2.5
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  firebase_storage: ^5.0.1
  flutter_bloc: ^6.1.1
  flutter_facebook_auth: ^1.0.1
  fluttertoast: ^7.1.1
  google_sign_in: ^4.5.6
  hydrated_bloc: ^6.1.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+14
  intl: ^0.16.1
  line_icons: ^0.2.0
  path: ^1.7.0
  purchases_flutter: ^1.4.3
  replay_bloc: ^0.0.1-dev.4
  rxdart: ^0.24.1
  share: '>=0.6.5+4 <2.0.0'
  shimmer: ^1.1.2
  sign_in_with_apple: ^2.5.4
  url_launcher: ^5.7.10
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  faker: ^1.2.1
  mockito: ^4.1.3
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
```
</details>

On iOS, `purchasePackage()` doesn't open up the product bottom sheet and just ends without throwing any exceptions. 
https://stackoverflow.com/questions/64561344/revenuecat-flutter-purchasepackage-does-not-work-but-there-are-no-exceptions
The above stackoverflow issue is exactly the same. Looks like this bug happens randomly. I can confirm that it works after I called it 3-5 times. I didn't test it on production yet and it happens in a sandbox environment.
